ALTER TABLE faction_state ALTER COLUMN id TYPE INTEGER;
ALTER TABLE controlling ALTER COLUMN id TYPE INTEGER;
ALTER TABLE system_power ALTER COLUMN id TYPE INTEGER;
ALTER TABLE presence ALTER COLUMN id TYPE INTEGER;
