ALTER TABLE faction_state ALTER COLUMN id TYPE BIGINT; 
ALTER TABLE controlling ALTER COLUMN id TYPE BIGINT; 
ALTER TABLE system_power ALTER COLUMN id TYPE BIGINT; 
ALTER TABLE presence ALTER COLUMN id TYPE BIGINT; 
